import { CommunityPost } from './community.types';

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
    {
        key: '1',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy this special arrangement for your loved ones with fresh roses.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Approved',
        likesCount: 142,
        commentsCount: 28,
        category: 'Birthday'
    },
    {
        key: '2',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy this exquisite handcrafted gift box made just for you.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Pending',
        likesCount: 35,
        commentsCount: 6,
        category: 'Gift Box'
    },
    {
        key: '3',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy our seasonal bouquet featuring vibrant spring lilies and roses.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Approved',
        likesCount: 215,
        commentsCount: 42,
        category: 'Bouquet'
    },
    {
        key: '4',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy a delightful combination of gourmet chocolates and fresh blooms.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Rejected',
        likesCount: 12,
        commentsCount: 2,
        category: 'Combos'
    },
    {
        key: '5',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy our premium luxury orchids arranged with decorative greenery.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Pending',
        likesCount: 68,
        commentsCount: 14,
        category: 'Luxury'
    },
    {
        key: '6',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Blossom Flowers',
        description: 'Happy Birthday! Enjoy customized floral baskets designed to brighten up any special day.',
        userName: 'Alice Smith',
        userEmail: 'alice@blossomflowers.com',
        submittedDate: '24-12-2025',
        status: 'Pending',
        likesCount: 89,
        commentsCount: 19,
        category: 'Baskets'
    },
    {
        key: '7',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Rose Haven',
        description: 'Anniversary Special! Surprise your partner with 24 long-stem red roses in a crystal vase.',
        userName: 'Michael Brown',
        userEmail: 'michael@rosehaven.com',
        submittedDate: '23-12-2025',
        status: 'Pending',
        likesCount: 54,
        commentsCount: 11,
        category: 'Anniversary'
    },
    {
        key: '8',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Orchid Sanctuary',
        description: 'Wedding Wishes! Elegant white orchids and calla lilies for a timeless celebration.',
        userName: 'Emma Wilson',
        userEmail: 'emma@orchidsanctuary.com',
        submittedDate: '22-12-2025',
        status: 'Approved',
        likesCount: 310,
        commentsCount: 65,
        category: 'Wedding'
    },
    {
        key: '9',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Sunflower Joy',
        description: 'Get Well Soon! Bright and cheerful sunflower bouquets guaranteed to bring a warm smile.',
        userName: 'David Miller',
        userEmail: 'david@sunflowerjoy.com',
        submittedDate: '21-12-2025',
        status: 'Pending',
        likesCount: 76,
        commentsCount: 15,
        category: 'Get Well'
    },
    {
        key: '10',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Floral Artistry',
        description: 'Congratulations! Celebrate big milestones with this grand celebratory floral arrangement.',
        userName: 'Sophia Davis',
        userEmail: 'sophia@floralartistry.com',
        submittedDate: '20-12-2025',
        status: 'Pending',
        likesCount: 94,
        commentsCount: 22,
        category: 'Celebration'
    },
    {
        key: '11',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Lily Delights',
        description: 'Thank You Gift! Show your heartfelt gratitude with fragrant oriental pink lilies.',
        userName: 'James Taylor',
        userEmail: 'james@lilydelights.com',
        submittedDate: '19-12-2025',
        status: 'Rejected',
        likesCount: 29,
        commentsCount: 4,
        category: 'Gratitude'
    },
    {
        key: '12',
        thumbnail: '/rose_bouquet.png',
        postTitle: 'Tulip Treasures',
        description: 'Spring Vibes! A colorful mix of Dutch tulips in a charming ceramic pot.',
        userName: 'Olivia Martinez',
        userEmail: 'olivia@tuliptreasures.com',
        submittedDate: '18-12-2025',
        status: 'Pending',
        likesCount: 112,
        commentsCount: 31,
        category: 'Spring'
    }
];
