import { Campaign } from './advertisement.types';

export const MOCK_CAMPAIGNS: Campaign[] = [
    {
        key: '1', adId: 'AD-1231', title: 'Minimalist Watch Ad', vendorName: 'Timepiece Curators',
        vendorEmail: 'timepiece@example.com', badge: 'NEW PRODUCT AD', price: 1200, duration: 3,
        paymentStatus: 'Paid', status: 'Pending', image: '/watch.jpg',
        startDate: '2026-06-20', endDate: '2026-06-23', sales: 'AED 4.5K',
        totalRevenue: 'AED 300', dailyAverage: 'AED 125', remainingDays: 0,
        placementSection: 'Mike Chen', placementEmail: 'mike.chen@example.com',
        rating: 4.9, reviewCount: 124, offer: 'Premium timepieces curated for you',
    },
    {
        key: '2', adId: 'AD-1232', title: 'Artisan Bouquet Featured', vendorName: 'Bloom & Co.',
        vendorEmail: 'bloom@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Pending', image: '/rose_bouquet.png',
        startDate: '2026-06-22', endDate: '2026-06-29', sales: 'AED 4.5K',
        totalRevenue: 'AED 420', dailyAverage: 'AED 60', remainingDays: 0,
        placementSection: 'Anna Lee', placementEmail: 'anna.l@example.com',
        rating: 4.7, reviewCount: 89, offer: 'Up to 30% off on premium bouquets',
    },
    {
        key: '3', adId: 'AD-1233', title: 'Valentine\'s Day Special', vendorName: 'Le Jardin Paris',
        vendorEmail: 'lejardin@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Pending', image: '/rose_bouquet.png',
        startDate: '2026-06-22', endDate: '2026-06-29', sales: 'AED 4.5K',
        totalRevenue: 'AED 300', dailyAverage: 'AED 43', remainingDays: 0,
        placementSection: 'Sarah Kim', placementEmail: 'sarah.k@example.com',
        rating: 4.8, reviewCount: 210, offer: 'Up to 30% off on premium bouquets',
    },
    {
        key: '4', adId: 'AD-1234', title: 'Summer Rose Collection', vendorName: 'Le Jardin Paris',
        vendorEmail: 'lejardin@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Pending', image: '/rose_bouquet.png',
        startDate: '2026-06-22', endDate: '2026-06-29', sales: 'AED 4.5K',
        totalRevenue: 'AED 510', dailyAverage: 'AED 73', remainingDays: 0,
        placementSection: 'James Don', placementEmail: 'james.d@example.com',
        rating: 4.6, reviewCount: 67, offer: 'Exclusive seasonal rose arrangements',
    },
    {
        key: '5', adId: 'AD-1235', title: 'Velvet Rose Collection', vendorName: 'Le Jardin Paris',
        vendorEmail: 'lejardin@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Active', image: '/rose_bouquet.png',
        startDate: '2026-06-18', endDate: '2026-06-25', sales: 'AED 4.5K',
        totalRevenue: 'AED 300', dailyAverage: 'AED 125', remainingDays: 2,
        placementSection: 'Mike Chen', placementEmail: 'mike.chen@example.com',
        rating: 4.9, reviewCount: 124, offer: 'Luxury velvet rose arrangements',
    },
    {
        key: '6', adId: 'AD-1236', title: 'Velvet Rose Collection', vendorName: 'Le Jardin Paris',
        vendorEmail: 'lejardin@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Expired', image: '/rose_bouquet.png',
        startDate: '2026-06-10', endDate: '2026-06-17', sales: 'AED 4.5K',
        totalRevenue: 'AED 595', dailyAverage: 'AED 85', remainingDays: 0,
        placementSection: 'Mike Chen', placementEmail: 'mike.chen@example.com',
        rating: 4.9, reviewCount: 124, offer: 'Luxury velvet rose arrangements',
    },
    {
        key: '7', adId: 'AD-1237', title: 'Velvet Rose Collection', vendorName: 'Le Jardin Paris',
        vendorEmail: 'lejardin@example.com', badge: 'FLASH SALE PROMO', price: 850, duration: 7,
        paymentStatus: 'Paid', status: 'Expired', image: '/rose_bouquet.png',
        startDate: '2026-06-01', endDate: '2026-06-08', sales: 'AED 4.5K',
        totalRevenue: 'AED 490', dailyAverage: 'AED 70', remainingDays: 0,
        placementSection: 'Mike Chen', placementEmail: 'mike.chen@example.com',
        rating: 4.9, reviewCount: 124, offer: 'Luxury velvet rose arrangements',
    },
];
