import { Vendor } from './vendors.types';

export const MOCK_VENDORS: Vendor[] = [
    {
        key: '1',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: 4.8,
        status: 'Approved',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    },
    {
        key: '2',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: 4.8,
        status: 'Approved',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    },
    {
        key: '3',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: null,
        status: 'Pending',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    },
    {
        key: '4',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: null,
        status: 'Pending',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    },
    {
        key: '5',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: 4.8,
        status: 'Approved',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    },
    {
        key: '6',
        storeName: 'Blossom Flowers',
        avatarLetter: 'B',
        productsCount: 48,
        ownerName: 'Alice Smith',
        ownerEmail: 'alice@blossomflowers.com',
        ownerPhone: '+1 555-0101',
        productsInList: 24,
        revenue: '$2,450.00',
        rating: 4.8,
        status: 'Suspended',
        joined: '2024-02-15',
        address: '456 Garden Street, New York, NY 10002',
        workingHours: '06:00 AM - 12:00 AM',
        pendingOrders: 12,
        completedOrders: 342,
        totalReviews: 156
    }
];
