import { Order } from './orders.types';

export const MOCK_ORDERS: Order[] = [
    {
        key: '1',
        orderId: '#ORD-1230',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$50.00',
        paymentMethod: 'Card',
        status: 'Delivered',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        isGift: false
    },
    {
        key: '2',
        orderId: '#ORD-2301',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$89.99',
        paymentMethod: 'Card',
        status: 'Processing',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        giftMessage: 'Happy Birthday! Hope you enjoy these chocolates!',
        isGift: true
    },
    {
        key: '3',
        orderId: '#ORD-1232',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$50.00',
        paymentMethod: 'Card',
        status: 'Pending',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        isGift: false
    },
    {
        key: '4',
        orderId: '#ORD-1233',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$50.00',
        paymentMethod: 'Card',
        status: 'Pending',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        isGift: false
    },
    {
        key: '5',
        orderId: '#ORD-1234',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$50.00',
        paymentMethod: 'Card',
        status: 'Cancelled',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        isGift: false
    },
    {
        key: '6',
        orderId: '#ORD-1235',
        orderDate: '2026-06-05',
        customerName: 'Sarah Johnson',
        customerEmail: 'sarah.j@example.com',
        customerPhone: '+1 234-567-8901',
        productName: 'Rose Bouquet Premium',
        quantity: 1,
        vendorName: 'Blossom Flowers',
        amount: '$50.00',
        paymentMethod: 'Card',
        status: 'Cancelled',
        address: '123 Main St, New York, NY 10001',
        trackingNumber: 'TRK-123456789',
        isGift: false
    }
];
